# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.cache/wt} [current_project]
set_property parent.project_path {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/sources_1/new/Half_adder.vhd}
  {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/sources_1/new/Full_adder.vhd}
  {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/sources_1/new/Ful_adder_16.vhd}
  {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/sources_1/new/ALU.vhd}
  {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/sources_1/new/Reg.vhd}
  {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/sources_1/new/Display_Controller.vhd}
  {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/sources_1/new/Debouncer.vhd}
  {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/sources_1/new/Clock_Divider.vhd}
  {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/sources_1/new/Multiplexor.vhd}
  {C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/sources_1/new/Basys3.vhd}
}
read_xdc {{C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/constrs_1/new/Basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/jnjor/Desktop/ob/Proyecto Base/Proyecto Base.srcs/constrs_1/new/Basys3.xdc}}]

synth_design -top Basys3 -part xc7a35tcpg236-1
write_checkpoint -noxdef Basys3.dcp
catch { report_utilization -file Basys3_utilization_synth.rpt -pb Basys3_utilization_synth.pb }
